version: '3.9'

services:
  apache:
    container_name: apache
    build: .
    volumes:
      - ./server/apache:/var/www/html
      - ./server/apache-conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80
    links:
      - db

  nginx:
    container_name: nginx-base
    image: nginx:latest
    working_dir: /usr/share/nginx/html
    volumes:
      - ./server/nginx:/usr/share/nginx/html-static
      - ./server/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'app_db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: '123456'
    ports:
      - 3306:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  adminer_mqsql:
    image: adminer
    ports:
      - 8081:8080